CREATE TABLE IF NOT EXISTS public.roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO public.roles (id, name) VALUES (1, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO public.roles (id, name) VALUES (2, 'DIRECTOR') ON CONFLICT DO NOTHING;
INSERT INTO public.roles (id, name) VALUES (3, 'ESTUDIANTE') ON CONFLICT DO NOTHING;